// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using Soenneker.Copper.OpenApiClient.Item.Item.Files;
using Soenneker.Copper.OpenApiClient.Item.Item.Related;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Soenneker.Copper.OpenApiClient.Item.Item
{
    /// <summary>
    /// Builds and executes requests for operations under \{entityNameInPlural-id}\{entityId}
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class WithEntityItemRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The files property</summary>
        public global::Soenneker.Copper.OpenApiClient.Item.Item.Files.FilesRequestBuilder Files
        {
            get => new global::Soenneker.Copper.OpenApiClient.Item.Item.Files.FilesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The related property</summary>
        public global::Soenneker.Copper.OpenApiClient.Item.Item.Related.RelatedRequestBuilder Related
        {
            get => new global::Soenneker.Copper.OpenApiClient.Item.Item.Related.RelatedRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Copper.OpenApiClient.Item.Item.WithEntityItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithEntityItemRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/{entityNameInPlural%2Did}/{entityId}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Copper.OpenApiClient.Item.Item.WithEntityItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithEntityItemRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/{entityNameInPlural%2Did}/{entityId}", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
