// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using Soenneker.Copper.OpenApiClient.Custom_field_definitions.Item;
using Soenneker.Copper.OpenApiClient.Models;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace Soenneker.Copper.OpenApiClient.Custom_field_definitions
{
    /// <summary>
    /// Builds and executes requests for operations under \custom_field_definitions
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class Custom_field_definitionsRequestBuilder : BaseRequestBuilder
    {
        /// <summary>Gets an item from the Soenneker.Copper.OpenApiClient.custom_field_definitions.item collection</summary>
        /// <param name="position">Unique identifier of the item</param>
        /// <returns>A <see cref="global::Soenneker.Copper.OpenApiClient.Custom_field_definitions.Item.WithCustomFieldDefinitionItemRequestBuilder"/></returns>
        public global::Soenneker.Copper.OpenApiClient.Custom_field_definitions.Item.WithCustomFieldDefinitionItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("customFieldDefinitionId", position);
                return new global::Soenneker.Copper.OpenApiClient.Custom_field_definitions.Item.WithCustomFieldDefinitionItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Copper.OpenApiClient.Custom_field_definitions.Custom_field_definitionsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public Custom_field_definitionsRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/custom_field_definitions", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Copper.OpenApiClient.Custom_field_definitions.Custom_field_definitionsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public Custom_field_definitionsRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/custom_field_definitions", rawUrl)
        {
        }
        /// <summary>
        /// Custom Field Definitions specify account specific fields not included as part of the standard resource fields and allows Copper to be customized to your specific workflow. The Custom Field Definitions API allows you to retrieve the list of Custom Field Definitions associated with your Copper account.|   Field   |     Type      |                                                                            Details                                                                             || --------- | ------------- | -------------------------------------------------------------------------------------------------------------------------------------------------------------- || id        | number        | Unique identifier for the custom field definition.                                                                                                            || name      | string        | Label for the custom field definition                                                                                                                          || data_type | string enum   | The type of data that should be stored within this custom field. Possible values are: String, Text, Dropdown, Date, Checkbox, Float, URL, Percentage, Currency, Connect || currency  | string enum   | The currency used for this custom field definition. Valid only when the data type is Currency.                                                                 || options   | options array | A list of possible dropdown options. Valid only when the data type is Dropdown.                                                                                |
        /// </summary>
        /// <returns>A List&lt;global::Soenneker.Copper.OpenApiClient.Models.ListCustomFieldDefinitions200ResponseItem&gt;</returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<List<global::Soenneker.Copper.OpenApiClient.Models.ListCustomFieldDefinitions200ResponseItem>?> GetAsync(Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<List<global::Soenneker.Copper.OpenApiClient.Models.ListCustomFieldDefinitions200ResponseItem>> GetAsync(Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            var collectionResult = await RequestAdapter.SendCollectionAsync<global::Soenneker.Copper.OpenApiClient.Models.ListCustomFieldDefinitions200ResponseItem>(requestInfo, global::Soenneker.Copper.OpenApiClient.Models.ListCustomFieldDefinitions200ResponseItem.CreateFromDiscriminatorValue, default, cancellationToken).ConfigureAwait(false);
            return collectionResult?.AsList();
        }
        /// <summary>
        /// | Field                 | Type          | Details | Default || --------------------- | ------------- | ----------------------- | ---------------------- || name*              | string | Name of the Custom Field Definition                     |                      || data_type*                  | string | One of the following strings: &quot;Checkbox&quot;, &quot;Currency&quot;, “Date&quot;, &quot;Dropdown&quot;, &quot;Float&quot;, &quot;MultiSelect&quot;, &quot;Percentage&quot;, “String&quot;, &quot;Text&quot;, &quot;URL&quot; |                      || available_on              | string array       | List of strings containing one or more of the following: “lead”, “person”, “opportunity”, “company”, &quot;project&quot;, &quot;task&quot;                      |                      || options          | integer array       | Array of options for Dropdown and MultiSelect fields.  A minimum of one option is required for Dropdown and a minimum of 2 options is required for MultiSelect                      |                      || currency            | string | 3-letter country code (e.g., &quot;USD&quot;, &quot;CAD&quot;)                     |                      ||\* indicates a required field| | |
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Copper.OpenApiClient.Models.CreateANewCustomFieldDefinition200Response"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Soenneker.Copper.OpenApiClient.Models.CreateANewCustomFieldDefinition200Response?> PostAsync(global::Soenneker.Copper.OpenApiClient.Models.CreateANewCustomFieldDefinitionRequest body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Soenneker.Copper.OpenApiClient.Models.CreateANewCustomFieldDefinition200Response> PostAsync(global::Soenneker.Copper.OpenApiClient.Models.CreateANewCustomFieldDefinitionRequest body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = ToPostRequestInformation(body, requestConfiguration);
            return await RequestAdapter.SendAsync<global::Soenneker.Copper.OpenApiClient.Models.CreateANewCustomFieldDefinition200Response>(requestInfo, global::Soenneker.Copper.OpenApiClient.Models.CreateANewCustomFieldDefinition200Response.CreateFromDiscriminatorValue, default, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Custom Field Definitions specify account specific fields not included as part of the standard resource fields and allows Copper to be customized to your specific workflow. The Custom Field Definitions API allows you to retrieve the list of Custom Field Definitions associated with your Copper account.|   Field   |     Type      |                                                                            Details                                                                             || --------- | ------------- | -------------------------------------------------------------------------------------------------------------------------------------------------------------- || id        | number        | Unique identifier for the custom field definition.                                                                                                            || name      | string        | Label for the custom field definition                                                                                                                          || data_type | string enum   | The type of data that should be stored within this custom field. Possible values are: String, Text, Dropdown, Date, Checkbox, Float, URL, Percentage, Currency, Connect || currency  | string enum   | The currency used for this custom field definition. Valid only when the data type is Currency.                                                                 || options   | options array | A list of possible dropdown options. Valid only when the data type is Dropdown.                                                                                |
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json;charset=utf-8");
            return requestInfo;
        }
        /// <summary>
        /// | Field                 | Type          | Details | Default || --------------------- | ------------- | ----------------------- | ---------------------- || name*              | string | Name of the Custom Field Definition                     |                      || data_type*                  | string | One of the following strings: &quot;Checkbox&quot;, &quot;Currency&quot;, “Date&quot;, &quot;Dropdown&quot;, &quot;Float&quot;, &quot;MultiSelect&quot;, &quot;Percentage&quot;, “String&quot;, &quot;Text&quot;, &quot;URL&quot; |                      || available_on              | string array       | List of strings containing one or more of the following: “lead”, “person”, “opportunity”, “company”, &quot;project&quot;, &quot;task&quot;                      |                      || options          | integer array       | Array of options for Dropdown and MultiSelect fields.  A minimum of one option is required for Dropdown and a minimum of 2 options is required for MultiSelect                      |                      || currency            | string | 3-letter country code (e.g., &quot;USD&quot;, &quot;CAD&quot;)                     |                      ||\* indicates a required field| | |
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToPostRequestInformation(global::Soenneker.Copper.OpenApiClient.Models.CreateANewCustomFieldDefinitionRequest body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToPostRequestInformation(global::Soenneker.Copper.OpenApiClient.Models.CreateANewCustomFieldDefinitionRequest body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = new RequestInformation(Method.POST, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json;charset=utf-8");
            requestInfo.SetContentFromParsable(RequestAdapter, "application/json", body);
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Copper.OpenApiClient.Custom_field_definitions.Custom_field_definitionsRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::Soenneker.Copper.OpenApiClient.Custom_field_definitions.Custom_field_definitionsRequestBuilder WithUrl(string rawUrl)
        {
            return new global::Soenneker.Copper.OpenApiClient.Custom_field_definitions.Custom_field_definitionsRequestBuilder(rawUrl, RequestAdapter);
        }
    }
}
#pragma warning restore CS0618
