// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using Soenneker.Copper.OpenApiClient.Item.Item;
using Soenneker.Copper.OpenApiClient.Item.Search;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Soenneker.Copper.OpenApiClient.Item
{
    /// <summary>
    /// Builds and executes requests for operations under \{entityNameInPlural-id}
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class EntityNameInPluralItemRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The search property</summary>
        public global::Soenneker.Copper.OpenApiClient.Item.Search.SearchRequestBuilder Search
        {
            get => new global::Soenneker.Copper.OpenApiClient.Item.Search.SearchRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>Gets an item from the Soenneker.Copper.OpenApiClient.item.item collection</summary>
        /// <param name="position">Unique identifier of the item</param>
        /// <returns>A <see cref="global::Soenneker.Copper.OpenApiClient.Item.Item.WithEntityItemRequestBuilder"/></returns>
        public global::Soenneker.Copper.OpenApiClient.Item.Item.WithEntityItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("entityId", position);
                return new global::Soenneker.Copper.OpenApiClient.Item.Item.WithEntityItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Copper.OpenApiClient.Item.EntityNameInPluralItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public EntityNameInPluralItemRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/{entityNameInPlural%2Did}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Copper.OpenApiClient.Item.EntityNameInPluralItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public EntityNameInPluralItemRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/{entityNameInPlural%2Did}", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
