// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using Soenneker.Copper.OpenApiClient.Models;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace Soenneker.Copper.OpenApiClient.Activities.Search
{
    /// <summary>
    /// Builds and executes requests for operations under \activities\search
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class SearchRequestBuilder : BaseRequestBuilder
    {
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Copper.OpenApiClient.Activities.Search.SearchRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public SearchRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/activities/search", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Copper.OpenApiClient.Activities.Search.SearchRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public SearchRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/activities/search", rawUrl)
        {
        }
        /// <summary>
        /// The /search endpoint provides the ability to list records and sort the results by certain parameters. When multiple ciriteria are provided records meeting ALL criteria will be returned (the filtering criteria have an &apos;AND&apos; relationship).To see examples of search request using the various parameters, click on the `Search Activities` dropdown on the right.Footnotes:1. Parent is specified by: {&quot;id&quot;: parent_id, &quot;type&quot;: parent_type}. &quot;parent_type&quot; can be &quot;lead&quot;, &quot;person&quot;, &quot;company&quot;, &quot;opportunity&quot;, &quot;project&quot;, &quot;task&quot;. 2. Activity types is specified by: {&quot;id&quot;: activity_type_id, &quot;category&quot;: category }. &quot;activity_type_id&quot; and &quot;category&quot; can be retrieved from `List Activity Types` under `Other Resources` folder.3. If the List Activities Search endpoint is timing out, a flag `full_result=true` can be added. One can expect to see multiple entries returned for the same activity if an email was sent to multiple users. In order to use this flag, user must have admin capabilities. Otherwise, the flag is ignored.
        /// </summary>
        /// <returns>A <see cref="string"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<string?> PostAsync(global::Soenneker.Copper.OpenApiClient.Models.PostActivitiesSearchRequest body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<string> PostAsync(global::Soenneker.Copper.OpenApiClient.Models.PostActivitiesSearchRequest body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = ToPostRequestInformation(body, requestConfiguration);
            return await RequestAdapter.SendPrimitiveAsync<string>(requestInfo, default, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// The /search endpoint provides the ability to list records and sort the results by certain parameters. When multiple ciriteria are provided records meeting ALL criteria will be returned (the filtering criteria have an &apos;AND&apos; relationship).To see examples of search request using the various parameters, click on the `Search Activities` dropdown on the right.Footnotes:1. Parent is specified by: {&quot;id&quot;: parent_id, &quot;type&quot;: parent_type}. &quot;parent_type&quot; can be &quot;lead&quot;, &quot;person&quot;, &quot;company&quot;, &quot;opportunity&quot;, &quot;project&quot;, &quot;task&quot;. 2. Activity types is specified by: {&quot;id&quot;: activity_type_id, &quot;category&quot;: category }. &quot;activity_type_id&quot; and &quot;category&quot; can be retrieved from `List Activity Types` under `Other Resources` folder.3. If the List Activities Search endpoint is timing out, a flag `full_result=true` can be added. One can expect to see multiple entries returned for the same activity if an email was sent to multiple users. In order to use this flag, user must have admin capabilities. Otherwise, the flag is ignored.
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToPostRequestInformation(global::Soenneker.Copper.OpenApiClient.Models.PostActivitiesSearchRequest body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToPostRequestInformation(global::Soenneker.Copper.OpenApiClient.Models.PostActivitiesSearchRequest body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = new RequestInformation(Method.POST, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            requestInfo.SetContentFromParsable(RequestAdapter, "application/json", body);
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Copper.OpenApiClient.Activities.Search.SearchRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::Soenneker.Copper.OpenApiClient.Activities.Search.SearchRequestBuilder WithUrl(string rawUrl)
        {
            return new global::Soenneker.Copper.OpenApiClient.Activities.Search.SearchRequestBuilder(rawUrl, RequestAdapter);
        }
    }
}
#pragma warning restore CS0618
