// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using Soenneker.Copper.OpenApiClient.Models;
using Soenneker.Copper.OpenApiClient.Pipeline_stages.Pipeline;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace Soenneker.Copper.OpenApiClient.Pipeline_stages
{
    /// <summary>
    /// Builds and executes requests for operations under \pipeline_stages
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class Pipeline_stagesRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The pipeline property</summary>
        public global::Soenneker.Copper.OpenApiClient.Pipeline_stages.Pipeline.PipelineRequestBuilder Pipeline
        {
            get => new global::Soenneker.Copper.OpenApiClient.Pipeline_stages.Pipeline.PipelineRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Copper.OpenApiClient.Pipeline_stages.Pipeline_stagesRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public Pipeline_stagesRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/pipeline_stages", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Copper.OpenApiClient.Pipeline_stages.Pipeline_stagesRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public Pipeline_stagesRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/pipeline_stages", rawUrl)
        {
        }
        /// <summary>
        /// Pipeline Stages define the positions of Opportunities within their Pipelines. The Pipeline Stages API allows you to retrieve the list of Pipeline Stages associated with your Copper account.|          Field           |                                                     Details                                                      || ------------------------ | ---------------------------------------------------------------------------------------------------------------- || id (number)              | Unique identifier for the Pipeline Stage.                                                                        || name (string)            | The name of the Pipeline Stage.                                                                                  || pipeline_id (number)     | The unique identifier of the Pipeline in which this Pipeline Stage is.                                           || win_probability (number) | The expected probability of winning an Opportunity in this Pipeline Stage. Valid values are [0-100] (inclusive). |
        /// </summary>
        /// <returns>A List&lt;global::Soenneker.Copper.OpenApiClient.Models.ListPipelineStages200ResponseItem&gt;</returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<List<global::Soenneker.Copper.OpenApiClient.Models.ListPipelineStages200ResponseItem>?> GetAsync(Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<List<global::Soenneker.Copper.OpenApiClient.Models.ListPipelineStages200ResponseItem>> GetAsync(Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            var collectionResult = await RequestAdapter.SendCollectionAsync<global::Soenneker.Copper.OpenApiClient.Models.ListPipelineStages200ResponseItem>(requestInfo, global::Soenneker.Copper.OpenApiClient.Models.ListPipelineStages200ResponseItem.CreateFromDiscriminatorValue, default, cancellationToken).ConfigureAwait(false);
            return collectionResult?.AsList();
        }
        /// <summary>
        /// Pipeline Stages define the positions of Opportunities within their Pipelines. The Pipeline Stages API allows you to retrieve the list of Pipeline Stages associated with your Copper account.|          Field           |                                                     Details                                                      || ------------------------ | ---------------------------------------------------------------------------------------------------------------- || id (number)              | Unique identifier for the Pipeline Stage.                                                                        || name (string)            | The name of the Pipeline Stage.                                                                                  || pipeline_id (number)     | The unique identifier of the Pipeline in which this Pipeline Stage is.                                           || win_probability (number) | The expected probability of winning an Opportunity in this Pipeline Stage. Valid values are [0-100] (inclusive). |
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json;charset=utf-8");
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Copper.OpenApiClient.Pipeline_stages.Pipeline_stagesRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::Soenneker.Copper.OpenApiClient.Pipeline_stages.Pipeline_stagesRequestBuilder WithUrl(string rawUrl)
        {
            return new global::Soenneker.Copper.OpenApiClient.Pipeline_stages.Pipeline_stagesRequestBuilder(rawUrl, RequestAdapter);
        }
    }
}
#pragma warning restore CS0618
