// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using Microsoft.Kiota.Serialization.Form;
using Microsoft.Kiota.Serialization.Json;
using Microsoft.Kiota.Serialization.Multipart;
using Microsoft.Kiota.Serialization.Text;
using Soenneker.Copper.OpenApiClient.Account;
using Soenneker.Copper.OpenApiClient.Activities;
using Soenneker.Copper.OpenApiClient.Activity_types;
using Soenneker.Copper.OpenApiClient.Companies;
using Soenneker.Copper.OpenApiClient.Contact_types;
using Soenneker.Copper.OpenApiClient.Custom_activity_types;
using Soenneker.Copper.OpenApiClient.Custom_field_definitions;
using Soenneker.Copper.OpenApiClient.Customer_sources;
using Soenneker.Copper.OpenApiClient.Item;
using Soenneker.Copper.OpenApiClient.Lead_statuses;
using Soenneker.Copper.OpenApiClient.Leads;
using Soenneker.Copper.OpenApiClient.Loss_reasons;
using Soenneker.Copper.OpenApiClient.Models;
using Soenneker.Copper.OpenApiClient.Opportunities;
using Soenneker.Copper.OpenApiClient.People;
using Soenneker.Copper.OpenApiClient.Pipeline_stages;
using Soenneker.Copper.OpenApiClient.Pipelines;
using Soenneker.Copper.OpenApiClient.Projects;
using Soenneker.Copper.OpenApiClient.Related_links;
using Soenneker.Copper.OpenApiClient.Tasks;
using Soenneker.Copper.OpenApiClient.Users;
using Soenneker.Copper.OpenApiClient.Webhooks;
using Soenneker.Copper.OpenApiClient.WebhooksWithExampleWebhookId;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace Soenneker.Copper.OpenApiClient
{
    /// <summary>
    /// The main entry point of the SDK, exposes the configuration and the fluent API.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class CopperOpenApiClient : BaseRequestBuilder
    {
        /// <summary>The account property</summary>
        public global::Soenneker.Copper.OpenApiClient.Account.AccountRequestBuilder Account
        {
            get => new global::Soenneker.Copper.OpenApiClient.Account.AccountRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The activities property</summary>
        public global::Soenneker.Copper.OpenApiClient.Activities.ActivitiesRequestBuilder Activities
        {
            get => new global::Soenneker.Copper.OpenApiClient.Activities.ActivitiesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The activity_types property</summary>
        public global::Soenneker.Copper.OpenApiClient.Activity_types.Activity_typesRequestBuilder Activity_types
        {
            get => new global::Soenneker.Copper.OpenApiClient.Activity_types.Activity_typesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The companies property</summary>
        public global::Soenneker.Copper.OpenApiClient.Companies.CompaniesRequestBuilder Companies
        {
            get => new global::Soenneker.Copper.OpenApiClient.Companies.CompaniesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The contact_types property</summary>
        public global::Soenneker.Copper.OpenApiClient.Contact_types.Contact_typesRequestBuilder Contact_types
        {
            get => new global::Soenneker.Copper.OpenApiClient.Contact_types.Contact_typesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The custom_activity_types property</summary>
        public global::Soenneker.Copper.OpenApiClient.Custom_activity_types.Custom_activity_typesRequestBuilder Custom_activity_types
        {
            get => new global::Soenneker.Copper.OpenApiClient.Custom_activity_types.Custom_activity_typesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The custom_field_definitions property</summary>
        public global::Soenneker.Copper.OpenApiClient.Custom_field_definitions.Custom_field_definitionsRequestBuilder Custom_field_definitions
        {
            get => new global::Soenneker.Copper.OpenApiClient.Custom_field_definitions.Custom_field_definitionsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The customer_sources property</summary>
        public global::Soenneker.Copper.OpenApiClient.Customer_sources.Customer_sourcesRequestBuilder Customer_sources
        {
            get => new global::Soenneker.Copper.OpenApiClient.Customer_sources.Customer_sourcesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The lead_statuses property</summary>
        public global::Soenneker.Copper.OpenApiClient.Lead_statuses.Lead_statusesRequestBuilder Lead_statuses
        {
            get => new global::Soenneker.Copper.OpenApiClient.Lead_statuses.Lead_statusesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The leads property</summary>
        public global::Soenneker.Copper.OpenApiClient.Leads.LeadsRequestBuilder Leads
        {
            get => new global::Soenneker.Copper.OpenApiClient.Leads.LeadsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The loss_reasons property</summary>
        public global::Soenneker.Copper.OpenApiClient.Loss_reasons.Loss_reasonsRequestBuilder Loss_reasons
        {
            get => new global::Soenneker.Copper.OpenApiClient.Loss_reasons.Loss_reasonsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The opportunities property</summary>
        public global::Soenneker.Copper.OpenApiClient.Opportunities.OpportunitiesRequestBuilder Opportunities
        {
            get => new global::Soenneker.Copper.OpenApiClient.Opportunities.OpportunitiesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The people property</summary>
        public global::Soenneker.Copper.OpenApiClient.People.PeopleRequestBuilder People
        {
            get => new global::Soenneker.Copper.OpenApiClient.People.PeopleRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The pipeline_stages property</summary>
        public global::Soenneker.Copper.OpenApiClient.Pipeline_stages.Pipeline_stagesRequestBuilder Pipeline_stages
        {
            get => new global::Soenneker.Copper.OpenApiClient.Pipeline_stages.Pipeline_stagesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The pipelines property</summary>
        public global::Soenneker.Copper.OpenApiClient.Pipelines.PipelinesRequestBuilder Pipelines
        {
            get => new global::Soenneker.Copper.OpenApiClient.Pipelines.PipelinesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The projects property</summary>
        public global::Soenneker.Copper.OpenApiClient.Projects.ProjectsRequestBuilder Projects
        {
            get => new global::Soenneker.Copper.OpenApiClient.Projects.ProjectsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The related_links property</summary>
        public global::Soenneker.Copper.OpenApiClient.Related_links.Related_linksRequestBuilder Related_links
        {
            get => new global::Soenneker.Copper.OpenApiClient.Related_links.Related_linksRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The tasks property</summary>
        public global::Soenneker.Copper.OpenApiClient.Tasks.TasksRequestBuilder Tasks
        {
            get => new global::Soenneker.Copper.OpenApiClient.Tasks.TasksRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The users property</summary>
        public global::Soenneker.Copper.OpenApiClient.Users.UsersRequestBuilder Users
        {
            get => new global::Soenneker.Copper.OpenApiClient.Users.UsersRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The webhooks property</summary>
        public global::Soenneker.Copper.OpenApiClient.Webhooks.WebhooksRequestBuilder Webhooks
        {
            get => new global::Soenneker.Copper.OpenApiClient.Webhooks.WebhooksRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>Gets an item from the Soenneker.Copper.OpenApiClient.item collection</summary>
        /// <param name="position">Unique identifier of the item</param>
        /// <returns>A <see cref="global::Soenneker.Copper.OpenApiClient.Item.EntityNameInPluralItemRequestBuilder"/></returns>
        public global::Soenneker.Copper.OpenApiClient.Item.EntityNameInPluralItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("entityNameInPlural%2Did", position);
                return new global::Soenneker.Copper.OpenApiClient.Item.EntityNameInPluralItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Copper.OpenApiClient.CopperOpenApiClient"/> and sets the default values.
        /// </summary>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public CopperOpenApiClient(IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}", new Dictionary<string, object>())
        {
            ApiClientBuilder.RegisterDefaultSerializer<JsonSerializationWriterFactory>();
            ApiClientBuilder.RegisterDefaultSerializer<TextSerializationWriterFactory>();
            ApiClientBuilder.RegisterDefaultSerializer<FormSerializationWriterFactory>();
            ApiClientBuilder.RegisterDefaultSerializer<MultipartSerializationWriterFactory>();
            ApiClientBuilder.RegisterDefaultDeserializer<JsonParseNodeFactory>();
            ApiClientBuilder.RegisterDefaultDeserializer<TextParseNodeFactory>();
            ApiClientBuilder.RegisterDefaultDeserializer<FormParseNodeFactory>();
            if (string.IsNullOrEmpty(RequestAdapter.BaseUrl))
            {
                RequestAdapter.BaseUrl = "https://api.copper.com/developer_api/v1";
            }
            PathParameters.TryAdd("baseurl", RequestAdapter.BaseUrl);
        }
        /// <summary>
        /// This example shows the notification request your endpoint will receive when a notification is sent. There can be 0 or more secret fields shown, depending on the initial webhook configuration. The &quot;updated_attributes&quot; field only shows up on an &quot;update&quot; event.
        /// </summary>
        /// <returns>A <see cref="Stream"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<Stream?> PostAsync(global::Soenneker.Copper.OpenApiClient.Models.PostRootPlainRequest body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<Stream> PostAsync(global::Soenneker.Copper.OpenApiClient.Models.PostRootPlainRequest body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = ToPostRequestInformation(body, requestConfiguration);
            return await RequestAdapter.SendPrimitiveAsync<Stream>(requestInfo, default, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// This example shows the notification request your endpoint will receive when a notification is sent. There can be 0 or more secret fields shown, depending on the initial webhook configuration. The &quot;updated_attributes&quot; field only shows up on an &quot;update&quot; event.
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToPostRequestInformation(global::Soenneker.Copper.OpenApiClient.Models.PostRootPlainRequest body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToPostRequestInformation(global::Soenneker.Copper.OpenApiClient.Models.PostRootPlainRequest body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = new RequestInformation(Method.POST, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.SetContentFromParsable(RequestAdapter, "text/plain", body);
            return requestInfo;
        }
        /// <summary>
        /// Builds and executes requests for operations under \webhooks{exampleWebhookId}
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Copper.OpenApiClient.WebhooksWithExampleWebhookId.WebhooksWithExampleWebhookIdRequestBuilder"/></returns>
        /// <param name="exampleWebhookId">The path parameter: exampleWebhookId</param>
        public global::Soenneker.Copper.OpenApiClient.WebhooksWithExampleWebhookId.WebhooksWithExampleWebhookIdRequestBuilder WebhooksWithExampleWebhookId(string exampleWebhookId)
        {
            if(string.IsNullOrEmpty(exampleWebhookId)) throw new ArgumentNullException(nameof(exampleWebhookId));
            return new global::Soenneker.Copper.OpenApiClient.WebhooksWithExampleWebhookId.WebhooksWithExampleWebhookIdRequestBuilder(PathParameters, RequestAdapter, exampleWebhookId);
        }
    }
}
#pragma warning restore CS0618
