// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using Soenneker.Copper.OpenApiClient.Models;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace Soenneker.Copper.OpenApiClient.Item.Search
{
    /// <summary>
    /// Builds and executes requests for operations under \{entityNameInPlural-id}\search
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class SearchRequestBuilder : BaseRequestBuilder
    {
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Copper.OpenApiClient.Item.Search.SearchRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public SearchRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/{entityNameInPlural%2Did}/search", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Copper.OpenApiClient.Item.Search.SearchRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public SearchRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/{entityNameInPlural%2Did}/search", rawUrl)
        {
        }
        /// <summary>
        /// Custom fields are available for each of the entities (Leads, People, Companies, Opportunities, Projects, and Tasks). Custom field types include: Text Field, Text Area, Dropdown, Date, Checkbox, Number Field, URL, Percentage, Currency, and Multi-Select Dropdown. Text fields are not searchable at this point. The table below summarizes the behavior of each of these fields.Except for text-related fields, each custom field can be searched via the dev API search endpoint for any of the entities. For Leads, this would be the endpoint `/leads/search`.Dropdown and Multi-Select Dropdown fields have the additional option of searching for records where dropdown and multi-select dropdown fields are empty. This can be accomplished by adding an additional field: { &quot;allow_empty&quot;: true }. Searching by Multi-select dropdown also allows searching if any, all, or none of the dropdown options are to be searched. These options can be used together.Examples of searching for each of the searchable fields can be found under the dropdown menu on the right. Examples given are for `Leads` and can be easily interchanged with any other entity.
        /// </summary>
        /// <returns>A <see cref="string"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<string?> PostAsync(global::Soenneker.Copper.OpenApiClient.Models.PostByEntityNameInPluralSearchRequest body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<string> PostAsync(global::Soenneker.Copper.OpenApiClient.Models.PostByEntityNameInPluralSearchRequest body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = ToPostRequestInformation(body, requestConfiguration);
            return await RequestAdapter.SendPrimitiveAsync<string>(requestInfo, default, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Custom fields are available for each of the entities (Leads, People, Companies, Opportunities, Projects, and Tasks). Custom field types include: Text Field, Text Area, Dropdown, Date, Checkbox, Number Field, URL, Percentage, Currency, and Multi-Select Dropdown. Text fields are not searchable at this point. The table below summarizes the behavior of each of these fields.Except for text-related fields, each custom field can be searched via the dev API search endpoint for any of the entities. For Leads, this would be the endpoint `/leads/search`.Dropdown and Multi-Select Dropdown fields have the additional option of searching for records where dropdown and multi-select dropdown fields are empty. This can be accomplished by adding an additional field: { &quot;allow_empty&quot;: true }. Searching by Multi-select dropdown also allows searching if any, all, or none of the dropdown options are to be searched. These options can be used together.Examples of searching for each of the searchable fields can be found under the dropdown menu on the right. Examples given are for `Leads` and can be easily interchanged with any other entity.
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToPostRequestInformation(global::Soenneker.Copper.OpenApiClient.Models.PostByEntityNameInPluralSearchRequest body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToPostRequestInformation(global::Soenneker.Copper.OpenApiClient.Models.PostByEntityNameInPluralSearchRequest body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = new RequestInformation(Method.POST, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            requestInfo.SetContentFromParsable(RequestAdapter, "application/json", body);
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Copper.OpenApiClient.Item.Search.SearchRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::Soenneker.Copper.OpenApiClient.Item.Search.SearchRequestBuilder WithUrl(string rawUrl)
        {
            return new global::Soenneker.Copper.OpenApiClient.Item.Search.SearchRequestBuilder(rawUrl, RequestAdapter);
        }
    }
}
#pragma warning restore CS0618
