// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using Soenneker.Copper.OpenApiClient.Models;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace Soenneker.Copper.OpenApiClient.Custom_field_definitions.Item
{
    /// <summary>
    /// Builds and executes requests for operations under \custom_field_definitions\{customFieldDefinitionId}
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class WithCustomFieldDefinitionItemRequestBuilder : BaseRequestBuilder
    {
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Copper.OpenApiClient.Custom_field_definitions.Item.WithCustomFieldDefinitionItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithCustomFieldDefinitionItemRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/custom_field_definitions/{customFieldDefinitionId}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Copper.OpenApiClient.Custom_field_definitions.Item.WithCustomFieldDefinitionItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithCustomFieldDefinitionItemRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/custom_field_definitions/{customFieldDefinitionId}", rawUrl)
        {
        }
        /// <summary>
        /// Delete a Custom Field Definition
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Copper.OpenApiClient.Models.DeleteACustomFieldDefinition200Response"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Soenneker.Copper.OpenApiClient.Models.DeleteACustomFieldDefinition200Response?> DeleteAsync(Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Soenneker.Copper.OpenApiClient.Models.DeleteACustomFieldDefinition200Response> DeleteAsync(Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToDeleteRequestInformation(requestConfiguration);
            return await RequestAdapter.SendAsync<global::Soenneker.Copper.OpenApiClient.Models.DeleteACustomFieldDefinition200Response>(requestInfo, global::Soenneker.Copper.OpenApiClient.Models.DeleteACustomFieldDefinition200Response.CreateFromDiscriminatorValue, default, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Fetch a Custom Field Definition
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Copper.OpenApiClient.Models.FetchACustomFieldDefinition200Response"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Soenneker.Copper.OpenApiClient.Models.FetchACustomFieldDefinition200Response?> GetAsync(Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Soenneker.Copper.OpenApiClient.Models.FetchACustomFieldDefinition200Response> GetAsync(Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            return await RequestAdapter.SendAsync<global::Soenneker.Copper.OpenApiClient.Models.FetchACustomFieldDefinition200Response>(requestInfo, global::Soenneker.Copper.OpenApiClient.Models.FetchACustomFieldDefinition200Response.CreateFromDiscriminatorValue, default, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// | Field                 | Type          | Details | Default || --------------------- | ------------- | ----------------------- | ---------------------- || name*              | string | Name of the Custom Field Definition                     |                      || data_type*                  | string | One of the following strings: &quot;Checkbox&quot;, &quot;Currency&quot;, “Date&quot;, &quot;Dropdown&quot;, &quot;Float&quot;, &quot;MultiSelect&quot;, &quot;Percentage&quot;, “String&quot;, &quot;Text&quot;, &quot;URL&quot; |                      || available_on              | string array       | List of strings containing one or more of the following: “lead”, “person”, “opportunity”, “company”, &quot;project&quot;, &quot;task&quot;                      |                      || options          | integer array       | Array of options for Dropdown and MultiSelect fields.  A minimum of one option is required for Dropdown and a minimum of 2 options is required for MultiSelect                      |                      || currency            | string | 3-letter country code (e.g., &quot;USD&quot;, &quot;CAD&quot;)                     |                      ||\* indicates a required field| | |
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Copper.OpenApiClient.Models.UpdateAnExistingCustomFieldDefinition200Response"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Soenneker.Copper.OpenApiClient.Models.UpdateAnExistingCustomFieldDefinition200Response?> PutAsync(global::Soenneker.Copper.OpenApiClient.Models.UpdateAnExistingCustomFieldDefinitionRequest body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Soenneker.Copper.OpenApiClient.Models.UpdateAnExistingCustomFieldDefinition200Response> PutAsync(global::Soenneker.Copper.OpenApiClient.Models.UpdateAnExistingCustomFieldDefinitionRequest body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = ToPutRequestInformation(body, requestConfiguration);
            return await RequestAdapter.SendAsync<global::Soenneker.Copper.OpenApiClient.Models.UpdateAnExistingCustomFieldDefinition200Response>(requestInfo, global::Soenneker.Copper.OpenApiClient.Models.UpdateAnExistingCustomFieldDefinition200Response.CreateFromDiscriminatorValue, default, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Delete a Custom Field Definition
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToDeleteRequestInformation(Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToDeleteRequestInformation(Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.DELETE, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json;charset=utf-8");
            return requestInfo;
        }
        /// <summary>
        /// Fetch a Custom Field Definition
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json;charset=utf-8");
            return requestInfo;
        }
        /// <summary>
        /// | Field                 | Type          | Details | Default || --------------------- | ------------- | ----------------------- | ---------------------- || name*              | string | Name of the Custom Field Definition                     |                      || data_type*                  | string | One of the following strings: &quot;Checkbox&quot;, &quot;Currency&quot;, “Date&quot;, &quot;Dropdown&quot;, &quot;Float&quot;, &quot;MultiSelect&quot;, &quot;Percentage&quot;, “String&quot;, &quot;Text&quot;, &quot;URL&quot; |                      || available_on              | string array       | List of strings containing one or more of the following: “lead”, “person”, “opportunity”, “company”, &quot;project&quot;, &quot;task&quot;                      |                      || options          | integer array       | Array of options for Dropdown and MultiSelect fields.  A minimum of one option is required for Dropdown and a minimum of 2 options is required for MultiSelect                      |                      || currency            | string | 3-letter country code (e.g., &quot;USD&quot;, &quot;CAD&quot;)                     |                      ||\* indicates a required field| | |
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToPutRequestInformation(global::Soenneker.Copper.OpenApiClient.Models.UpdateAnExistingCustomFieldDefinitionRequest body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToPutRequestInformation(global::Soenneker.Copper.OpenApiClient.Models.UpdateAnExistingCustomFieldDefinitionRequest body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = new RequestInformation(Method.PUT, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json;charset=utf-8");
            requestInfo.SetContentFromParsable(RequestAdapter, "application/json", body);
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Copper.OpenApiClient.Custom_field_definitions.Item.WithCustomFieldDefinitionItemRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::Soenneker.Copper.OpenApiClient.Custom_field_definitions.Item.WithCustomFieldDefinitionItemRequestBuilder WithUrl(string rawUrl)
        {
            return new global::Soenneker.Copper.OpenApiClient.Custom_field_definitions.Item.WithCustomFieldDefinitionItemRequestBuilder(rawUrl, RequestAdapter);
        }
    }
}
#pragma warning restore CS0618
