// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Copper.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class CreateANewOpportunity200Response : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The assignee_id property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? AssigneeId { get; set; }
#nullable restore
#else
        public string AssigneeId { get; set; }
#endif
        /// <summary>The close_date property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CloseDate { get; set; }
#nullable restore
#else
        public string CloseDate { get; set; }
#endif
        /// <summary>The company_id property</summary>
        public int? CompanyId { get; set; }
        /// <summary>The company_name property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CompanyName { get; set; }
#nullable restore
#else
        public string CompanyName { get; set; }
#endif
        /// <summary>The customer_source_id property</summary>
        public int? CustomerSourceId { get; set; }
        /// <summary>The custom_fields property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Copper.OpenApiClient.Models.CreateANewOpportunity200ResponseCustomFieldsItem>? CustomFields { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Copper.OpenApiClient.Models.CreateANewOpportunity200ResponseCustomFieldsItem> CustomFields { get; set; }
#endif
        /// <summary>The date_created property</summary>
        public int? DateCreated { get; set; }
        /// <summary>The date_last_contacted property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? DateLastContacted { get; set; }
#nullable restore
#else
        public string DateLastContacted { get; set; }
#endif
        /// <summary>The date_modified property</summary>
        public int? DateModified { get; set; }
        /// <summary>The details property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Details { get; set; }
#nullable restore
#else
        public string Details { get; set; }
#endif
        /// <summary>The id property</summary>
        public int? Id { get; set; }
        /// <summary>The interaction_count property</summary>
        public int? InteractionCount { get; set; }
        /// <summary>The leads_converted_from property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? LeadsConvertedFrom { get; set; }
#nullable restore
#else
        public List<string> LeadsConvertedFrom { get; set; }
#endif
        /// <summary>The loss_reason_id property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? LossReasonId { get; set; }
#nullable restore
#else
        public string LossReasonId { get; set; }
#endif
        /// <summary>The monetary_value property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? MonetaryValue { get; set; }
#nullable restore
#else
        public string MonetaryValue { get; set; }
#endif
        /// <summary>The name property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Name { get; set; }
#nullable restore
#else
        public string Name { get; set; }
#endif
        /// <summary>The pipeline_id property</summary>
        public int? PipelineId { get; set; }
        /// <summary>The pipeline_stage_id property</summary>
        public int? PipelineStageId { get; set; }
        /// <summary>The primary_contact_id property</summary>
        public int? PrimaryContactId { get; set; }
        /// <summary>The priority property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Priority { get; set; }
#nullable restore
#else
        public string Priority { get; set; }
#endif
        /// <summary>The status property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Status { get; set; }
#nullable restore
#else
        public string Status { get; set; }
#endif
        /// <summary>The tags property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? Tags { get; set; }
#nullable restore
#else
        public List<string> Tags { get; set; }
#endif
        /// <summary>The win_probability property</summary>
        public int? WinProbability { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Copper.OpenApiClient.Models.CreateANewOpportunity200Response"/> and sets the default values.
        /// </summary>
        public CreateANewOpportunity200Response()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Copper.OpenApiClient.Models.CreateANewOpportunity200Response"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Copper.OpenApiClient.Models.CreateANewOpportunity200Response CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Copper.OpenApiClient.Models.CreateANewOpportunity200Response();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "assignee_id", n => { AssigneeId = n.GetStringValue(); } },
                { "close_date", n => { CloseDate = n.GetStringValue(); } },
                { "company_id", n => { CompanyId = n.GetIntValue(); } },
                { "company_name", n => { CompanyName = n.GetStringValue(); } },
                { "custom_fields", n => { CustomFields = n.GetCollectionOfObjectValues<global::Soenneker.Copper.OpenApiClient.Models.CreateANewOpportunity200ResponseCustomFieldsItem>(global::Soenneker.Copper.OpenApiClient.Models.CreateANewOpportunity200ResponseCustomFieldsItem.CreateFromDiscriminatorValue)?.AsList(); } },
                { "customer_source_id", n => { CustomerSourceId = n.GetIntValue(); } },
                { "date_created", n => { DateCreated = n.GetIntValue(); } },
                { "date_last_contacted", n => { DateLastContacted = n.GetStringValue(); } },
                { "date_modified", n => { DateModified = n.GetIntValue(); } },
                { "details", n => { Details = n.GetStringValue(); } },
                { "id", n => { Id = n.GetIntValue(); } },
                { "interaction_count", n => { InteractionCount = n.GetIntValue(); } },
                { "leads_converted_from", n => { LeadsConvertedFrom = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "loss_reason_id", n => { LossReasonId = n.GetStringValue(); } },
                { "monetary_value", n => { MonetaryValue = n.GetStringValue(); } },
                { "name", n => { Name = n.GetStringValue(); } },
                { "pipeline_id", n => { PipelineId = n.GetIntValue(); } },
                { "pipeline_stage_id", n => { PipelineStageId = n.GetIntValue(); } },
                { "primary_contact_id", n => { PrimaryContactId = n.GetIntValue(); } },
                { "priority", n => { Priority = n.GetStringValue(); } },
                { "status", n => { Status = n.GetStringValue(); } },
                { "tags", n => { Tags = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "win_probability", n => { WinProbability = n.GetIntValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("assignee_id", AssigneeId);
            writer.WriteStringValue("close_date", CloseDate);
            writer.WriteIntValue("company_id", CompanyId);
            writer.WriteStringValue("company_name", CompanyName);
            writer.WriteIntValue("customer_source_id", CustomerSourceId);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Copper.OpenApiClient.Models.CreateANewOpportunity200ResponseCustomFieldsItem>("custom_fields", CustomFields);
            writer.WriteIntValue("date_created", DateCreated);
            writer.WriteStringValue("date_last_contacted", DateLastContacted);
            writer.WriteIntValue("date_modified", DateModified);
            writer.WriteStringValue("details", Details);
            writer.WriteIntValue("id", Id);
            writer.WriteIntValue("interaction_count", InteractionCount);
            writer.WriteCollectionOfPrimitiveValues<string>("leads_converted_from", LeadsConvertedFrom);
            writer.WriteStringValue("loss_reason_id", LossReasonId);
            writer.WriteStringValue("monetary_value", MonetaryValue);
            writer.WriteStringValue("name", Name);
            writer.WriteIntValue("pipeline_id", PipelineId);
            writer.WriteIntValue("pipeline_stage_id", PipelineStageId);
            writer.WriteIntValue("primary_contact_id", PrimaryContactId);
            writer.WriteStringValue("priority", Priority);
            writer.WriteStringValue("status", Status);
            writer.WriteCollectionOfPrimitiveValues<string>("tags", Tags);
            writer.WriteIntValue("win_probability", WinProbability);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
