// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Copper.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class FetchALeadById200Response : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The address property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Copper.OpenApiClient.Models.FetchALeadById200ResponseAddress? Address { get; set; }
#nullable restore
#else
        public global::Soenneker.Copper.OpenApiClient.Models.FetchALeadById200ResponseAddress Address { get; set; }
#endif
        /// <summary>The assignee_id property</summary>
        public int? AssigneeId { get; set; }
        /// <summary>The company_name property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CompanyName { get; set; }
#nullable restore
#else
        public string CompanyName { get; set; }
#endif
        /// <summary>The customer_source_id property</summary>
        public int? CustomerSourceId { get; set; }
        /// <summary>The custom_fields property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Copper.OpenApiClient.Models.FetchALeadById200ResponseCustomFieldsItem>? CustomFields { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Copper.OpenApiClient.Models.FetchALeadById200ResponseCustomFieldsItem> CustomFields { get; set; }
#endif
        /// <summary>The date_created property</summary>
        public int? DateCreated { get; set; }
        /// <summary>The date_modified property</summary>
        public int? DateModified { get; set; }
        /// <summary>The details property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Details { get; set; }
#nullable restore
#else
        public string Details { get; set; }
#endif
        /// <summary>The email property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Copper.OpenApiClient.Models.FetchALeadById200ResponseEmail? Email { get; set; }
#nullable restore
#else
        public global::Soenneker.Copper.OpenApiClient.Models.FetchALeadById200ResponseEmail Email { get; set; }
#endif
        /// <summary>The first_name property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? FirstName { get; set; }
#nullable restore
#else
        public string FirstName { get; set; }
#endif
        /// <summary>The id property</summary>
        public int? Id { get; set; }
        /// <summary>The last_name property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? LastName { get; set; }
#nullable restore
#else
        public string LastName { get; set; }
#endif
        /// <summary>The middle_name property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? MiddleName { get; set; }
#nullable restore
#else
        public string MiddleName { get; set; }
#endif
        /// <summary>The monetary_value property</summary>
        public int? MonetaryValue { get; set; }
        /// <summary>The name property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Name { get; set; }
#nullable restore
#else
        public string Name { get; set; }
#endif
        /// <summary>The phone_numbers property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Copper.OpenApiClient.Models.FetchALeadById200ResponsePhoneNumbersItem>? PhoneNumbers { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Copper.OpenApiClient.Models.FetchALeadById200ResponsePhoneNumbersItem> PhoneNumbers { get; set; }
#endif
        /// <summary>The prefix property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Prefix { get; set; }
#nullable restore
#else
        public string Prefix { get; set; }
#endif
        /// <summary>The socials property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Copper.OpenApiClient.Models.FetchALeadById200ResponseSocialsItem>? Socials { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Copper.OpenApiClient.Models.FetchALeadById200ResponseSocialsItem> Socials { get; set; }
#endif
        /// <summary>The status property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Status { get; set; }
#nullable restore
#else
        public string Status { get; set; }
#endif
        /// <summary>The status_id property</summary>
        public int? StatusId { get; set; }
        /// <summary>The suffix property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Suffix { get; set; }
#nullable restore
#else
        public string Suffix { get; set; }
#endif
        /// <summary>The tags property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? Tags { get; set; }
#nullable restore
#else
        public List<string> Tags { get; set; }
#endif
        /// <summary>The title property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Title { get; set; }
#nullable restore
#else
        public string Title { get; set; }
#endif
        /// <summary>The websites property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Copper.OpenApiClient.Models.FetchALeadById200ResponseWebsitesItem>? Websites { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Copper.OpenApiClient.Models.FetchALeadById200ResponseWebsitesItem> Websites { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Copper.OpenApiClient.Models.FetchALeadById200Response"/> and sets the default values.
        /// </summary>
        public FetchALeadById200Response()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Copper.OpenApiClient.Models.FetchALeadById200Response"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Copper.OpenApiClient.Models.FetchALeadById200Response CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Copper.OpenApiClient.Models.FetchALeadById200Response();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "address", n => { Address = n.GetObjectValue<global::Soenneker.Copper.OpenApiClient.Models.FetchALeadById200ResponseAddress>(global::Soenneker.Copper.OpenApiClient.Models.FetchALeadById200ResponseAddress.CreateFromDiscriminatorValue); } },
                { "assignee_id", n => { AssigneeId = n.GetIntValue(); } },
                { "company_name", n => { CompanyName = n.GetStringValue(); } },
                { "custom_fields", n => { CustomFields = n.GetCollectionOfObjectValues<global::Soenneker.Copper.OpenApiClient.Models.FetchALeadById200ResponseCustomFieldsItem>(global::Soenneker.Copper.OpenApiClient.Models.FetchALeadById200ResponseCustomFieldsItem.CreateFromDiscriminatorValue)?.AsList(); } },
                { "customer_source_id", n => { CustomerSourceId = n.GetIntValue(); } },
                { "date_created", n => { DateCreated = n.GetIntValue(); } },
                { "date_modified", n => { DateModified = n.GetIntValue(); } },
                { "details", n => { Details = n.GetStringValue(); } },
                { "email", n => { Email = n.GetObjectValue<global::Soenneker.Copper.OpenApiClient.Models.FetchALeadById200ResponseEmail>(global::Soenneker.Copper.OpenApiClient.Models.FetchALeadById200ResponseEmail.CreateFromDiscriminatorValue); } },
                { "first_name", n => { FirstName = n.GetStringValue(); } },
                { "id", n => { Id = n.GetIntValue(); } },
                { "last_name", n => { LastName = n.GetStringValue(); } },
                { "middle_name", n => { MiddleName = n.GetStringValue(); } },
                { "monetary_value", n => { MonetaryValue = n.GetIntValue(); } },
                { "name", n => { Name = n.GetStringValue(); } },
                { "phone_numbers", n => { PhoneNumbers = n.GetCollectionOfObjectValues<global::Soenneker.Copper.OpenApiClient.Models.FetchALeadById200ResponsePhoneNumbersItem>(global::Soenneker.Copper.OpenApiClient.Models.FetchALeadById200ResponsePhoneNumbersItem.CreateFromDiscriminatorValue)?.AsList(); } },
                { "prefix", n => { Prefix = n.GetStringValue(); } },
                { "socials", n => { Socials = n.GetCollectionOfObjectValues<global::Soenneker.Copper.OpenApiClient.Models.FetchALeadById200ResponseSocialsItem>(global::Soenneker.Copper.OpenApiClient.Models.FetchALeadById200ResponseSocialsItem.CreateFromDiscriminatorValue)?.AsList(); } },
                { "status", n => { Status = n.GetStringValue(); } },
                { "status_id", n => { StatusId = n.GetIntValue(); } },
                { "suffix", n => { Suffix = n.GetStringValue(); } },
                { "tags", n => { Tags = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "title", n => { Title = n.GetStringValue(); } },
                { "websites", n => { Websites = n.GetCollectionOfObjectValues<global::Soenneker.Copper.OpenApiClient.Models.FetchALeadById200ResponseWebsitesItem>(global::Soenneker.Copper.OpenApiClient.Models.FetchALeadById200ResponseWebsitesItem.CreateFromDiscriminatorValue)?.AsList(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::Soenneker.Copper.OpenApiClient.Models.FetchALeadById200ResponseAddress>("address", Address);
            writer.WriteIntValue("assignee_id", AssigneeId);
            writer.WriteStringValue("company_name", CompanyName);
            writer.WriteIntValue("customer_source_id", CustomerSourceId);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Copper.OpenApiClient.Models.FetchALeadById200ResponseCustomFieldsItem>("custom_fields", CustomFields);
            writer.WriteIntValue("date_created", DateCreated);
            writer.WriteIntValue("date_modified", DateModified);
            writer.WriteStringValue("details", Details);
            writer.WriteObjectValue<global::Soenneker.Copper.OpenApiClient.Models.FetchALeadById200ResponseEmail>("email", Email);
            writer.WriteStringValue("first_name", FirstName);
            writer.WriteIntValue("id", Id);
            writer.WriteStringValue("last_name", LastName);
            writer.WriteStringValue("middle_name", MiddleName);
            writer.WriteIntValue("monetary_value", MonetaryValue);
            writer.WriteStringValue("name", Name);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Copper.OpenApiClient.Models.FetchALeadById200ResponsePhoneNumbersItem>("phone_numbers", PhoneNumbers);
            writer.WriteStringValue("prefix", Prefix);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Copper.OpenApiClient.Models.FetchALeadById200ResponseSocialsItem>("socials", Socials);
            writer.WriteStringValue("status", Status);
            writer.WriteIntValue("status_id", StatusId);
            writer.WriteStringValue("suffix", Suffix);
            writer.WriteCollectionOfPrimitiveValues<string>("tags", Tags);
            writer.WriteStringValue("title", Title);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Copper.OpenApiClient.Models.FetchALeadById200ResponseWebsitesItem>("websites", Websites);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
