// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Copper.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class ListTheConnectionsOnSpecifiedEntity200ResponseItem : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The custom_field_definition_id property</summary>
        public int? CustomFieldDefinitionId { get; set; }
        /// <summary>The id property</summary>
        public int? Id { get; set; }
        /// <summary>The source property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Copper.OpenApiClient.Models.ListTheConnectionsOnSpecifiedEntity200ResponseItemSource? Source { get; set; }
#nullable restore
#else
        public global::Soenneker.Copper.OpenApiClient.Models.ListTheConnectionsOnSpecifiedEntity200ResponseItemSource Source { get; set; }
#endif
        /// <summary>The target property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Copper.OpenApiClient.Models.ListTheConnectionsOnSpecifiedEntity200ResponseItemTarget? Target { get; set; }
#nullable restore
#else
        public global::Soenneker.Copper.OpenApiClient.Models.ListTheConnectionsOnSpecifiedEntity200ResponseItemTarget Target { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Copper.OpenApiClient.Models.ListTheConnectionsOnSpecifiedEntity200ResponseItem"/> and sets the default values.
        /// </summary>
        public ListTheConnectionsOnSpecifiedEntity200ResponseItem()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Copper.OpenApiClient.Models.ListTheConnectionsOnSpecifiedEntity200ResponseItem"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Copper.OpenApiClient.Models.ListTheConnectionsOnSpecifiedEntity200ResponseItem CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Copper.OpenApiClient.Models.ListTheConnectionsOnSpecifiedEntity200ResponseItem();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "custom_field_definition_id", n => { CustomFieldDefinitionId = n.GetIntValue(); } },
                { "id", n => { Id = n.GetIntValue(); } },
                { "source", n => { Source = n.GetObjectValue<global::Soenneker.Copper.OpenApiClient.Models.ListTheConnectionsOnSpecifiedEntity200ResponseItemSource>(global::Soenneker.Copper.OpenApiClient.Models.ListTheConnectionsOnSpecifiedEntity200ResponseItemSource.CreateFromDiscriminatorValue); } },
                { "target", n => { Target = n.GetObjectValue<global::Soenneker.Copper.OpenApiClient.Models.ListTheConnectionsOnSpecifiedEntity200ResponseItemTarget>(global::Soenneker.Copper.OpenApiClient.Models.ListTheConnectionsOnSpecifiedEntity200ResponseItemTarget.CreateFromDiscriminatorValue); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteIntValue("custom_field_definition_id", CustomFieldDefinitionId);
            writer.WriteIntValue("id", Id);
            writer.WriteObjectValue<global::Soenneker.Copper.OpenApiClient.Models.ListTheConnectionsOnSpecifiedEntity200ResponseItemSource>("source", Source);
            writer.WriteObjectValue<global::Soenneker.Copper.OpenApiClient.Models.ListTheConnectionsOnSpecifiedEntity200ResponseItemTarget>("target", Target);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
