// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Copper.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class ListTasksSearch200ResponseItem : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The assignee_id property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? AssigneeId { get; set; }
#nullable restore
#else
        public string AssigneeId { get; set; }
#endif
        /// <summary>The completed_date property</summary>
        public int? CompletedDate { get; set; }
        /// <summary>The custom_activity_type_id property</summary>
        public int? CustomActivityTypeId { get; set; }
        /// <summary>The custom_fields property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Copper.OpenApiClient.Models.ListTasksSearch200ResponseItemCustomFieldsItem>? CustomFields { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Copper.OpenApiClient.Models.ListTasksSearch200ResponseItemCustomFieldsItem> CustomFields { get; set; }
#endif
        /// <summary>The date_created property</summary>
        public int? DateCreated { get; set; }
        /// <summary>The date_modified property</summary>
        public int? DateModified { get; set; }
        /// <summary>The details property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Details { get; set; }
#nullable restore
#else
        public string Details { get; set; }
#endif
        /// <summary>The due_date property</summary>
        public int? DueDate { get; set; }
        /// <summary>The id property</summary>
        public int? Id { get; set; }
        /// <summary>The name property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Name { get; set; }
#nullable restore
#else
        public string Name { get; set; }
#endif
        /// <summary>The priority property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Priority { get; set; }
#nullable restore
#else
        public string Priority { get; set; }
#endif
        /// <summary>The related_resource property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Copper.OpenApiClient.Models.ListTasksSearch200ResponseItemRelatedResource? RelatedResource { get; set; }
#nullable restore
#else
        public global::Soenneker.Copper.OpenApiClient.Models.ListTasksSearch200ResponseItemRelatedResource RelatedResource { get; set; }
#endif
        /// <summary>The reminder_date property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ReminderDate { get; set; }
#nullable restore
#else
        public string ReminderDate { get; set; }
#endif
        /// <summary>The status property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Status { get; set; }
#nullable restore
#else
        public string Status { get; set; }
#endif
        /// <summary>The tags property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? Tags { get; set; }
#nullable restore
#else
        public List<string> Tags { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Copper.OpenApiClient.Models.ListTasksSearch200ResponseItem"/> and sets the default values.
        /// </summary>
        public ListTasksSearch200ResponseItem()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Copper.OpenApiClient.Models.ListTasksSearch200ResponseItem"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Copper.OpenApiClient.Models.ListTasksSearch200ResponseItem CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Copper.OpenApiClient.Models.ListTasksSearch200ResponseItem();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "assignee_id", n => { AssigneeId = n.GetStringValue(); } },
                { "completed_date", n => { CompletedDate = n.GetIntValue(); } },
                { "custom_activity_type_id", n => { CustomActivityTypeId = n.GetIntValue(); } },
                { "custom_fields", n => { CustomFields = n.GetCollectionOfObjectValues<global::Soenneker.Copper.OpenApiClient.Models.ListTasksSearch200ResponseItemCustomFieldsItem>(global::Soenneker.Copper.OpenApiClient.Models.ListTasksSearch200ResponseItemCustomFieldsItem.CreateFromDiscriminatorValue)?.AsList(); } },
                { "date_created", n => { DateCreated = n.GetIntValue(); } },
                { "date_modified", n => { DateModified = n.GetIntValue(); } },
                { "details", n => { Details = n.GetStringValue(); } },
                { "due_date", n => { DueDate = n.GetIntValue(); } },
                { "id", n => { Id = n.GetIntValue(); } },
                { "name", n => { Name = n.GetStringValue(); } },
                { "priority", n => { Priority = n.GetStringValue(); } },
                { "related_resource", n => { RelatedResource = n.GetObjectValue<global::Soenneker.Copper.OpenApiClient.Models.ListTasksSearch200ResponseItemRelatedResource>(global::Soenneker.Copper.OpenApiClient.Models.ListTasksSearch200ResponseItemRelatedResource.CreateFromDiscriminatorValue); } },
                { "reminder_date", n => { ReminderDate = n.GetStringValue(); } },
                { "status", n => { Status = n.GetStringValue(); } },
                { "tags", n => { Tags = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("assignee_id", AssigneeId);
            writer.WriteIntValue("completed_date", CompletedDate);
            writer.WriteIntValue("custom_activity_type_id", CustomActivityTypeId);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Copper.OpenApiClient.Models.ListTasksSearch200ResponseItemCustomFieldsItem>("custom_fields", CustomFields);
            writer.WriteIntValue("date_created", DateCreated);
            writer.WriteIntValue("date_modified", DateModified);
            writer.WriteStringValue("details", Details);
            writer.WriteIntValue("due_date", DueDate);
            writer.WriteIntValue("id", Id);
            writer.WriteStringValue("name", Name);
            writer.WriteStringValue("priority", Priority);
            writer.WriteObjectValue<global::Soenneker.Copper.OpenApiClient.Models.ListTasksSearch200ResponseItemRelatedResource>("related_resource", RelatedResource);
            writer.WriteStringValue("reminder_date", ReminderDate);
            writer.WriteStringValue("status", Status);
            writer.WriteCollectionOfPrimitiveValues<string>("tags", Tags);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
