// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Copper.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class ListOpportunitiesSearch200ResponseItem : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The assignee_id property</summary>
        public long? AssigneeId { get; set; }
        /// <summary>The close_date property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CloseDate { get; set; }
#nullable restore
#else
        public string CloseDate { get; set; }
#endif
        /// <summary>The company_id property</summary>
        public long? CompanyId { get; set; }
        /// <summary>The company_name property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CompanyName { get; set; }
#nullable restore
#else
        public string CompanyName { get; set; }
#endif
        /// <summary>The customer_source_id property</summary>
        public long? CustomerSourceId { get; set; }
        /// <summary>The custom_fields property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Copper.OpenApiClient.Models.ListOpportunitiesSearch200ResponseItemCustomFieldsItem>? CustomFields { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Copper.OpenApiClient.Models.ListOpportunitiesSearch200ResponseItemCustomFieldsItem> CustomFields { get; set; }
#endif
        /// <summary>The date_created property</summary>
        public long? DateCreated { get; set; }
        /// <summary>The date_last_contacted property</summary>
        public long? DateLastContacted { get; set; }
        /// <summary>The date_lead_created property</summary>
        public long? DateLeadCreated { get; set; }
        /// <summary>The date_modified property</summary>
        public long? DateModified { get; set; }
        /// <summary>The date_stage_changed property</summary>
        public long? DateStageChanged { get; set; }
        /// <summary>The details property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Details { get; set; }
#nullable restore
#else
        public string Details { get; set; }
#endif
        /// <summary>The id property</summary>
        public long? Id { get; set; }
        /// <summary>The interaction_count property</summary>
        public long? InteractionCount { get; set; }
        /// <summary>The leads_converted_from property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Copper.OpenApiClient.Models.ListOpportunitiesSearch200ResponseItemLeadsConvertedFromItem>? LeadsConvertedFrom { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Copper.OpenApiClient.Models.ListOpportunitiesSearch200ResponseItemLeadsConvertedFromItem> LeadsConvertedFrom { get; set; }
#endif
        /// <summary>The loss_reason_id property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public UntypedNode? LossReasonId { get; set; }
#nullable restore
#else
        public UntypedNode LossReasonId { get; set; }
#endif
        /// <summary>The monetary_unit property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? MonetaryUnit { get; set; }
#nullable restore
#else
        public string MonetaryUnit { get; set; }
#endif
        /// <summary>The monetary_value property</summary>
        public long? MonetaryValue { get; set; }
        /// <summary>The name property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Name { get; set; }
#nullable restore
#else
        public string Name { get; set; }
#endif
        /// <summary>The pipeline_id property</summary>
        public long? PipelineId { get; set; }
        /// <summary>The pipeline_stage_id property</summary>
        public long? PipelineStageId { get; set; }
        /// <summary>The primary_contact_id property</summary>
        public long? PrimaryContactId { get; set; }
        /// <summary>The priority property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Priority { get; set; }
#nullable restore
#else
        public string Priority { get; set; }
#endif
        /// <summary>The status property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Status { get; set; }
#nullable restore
#else
        public string Status { get; set; }
#endif
        /// <summary>The tags property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? Tags { get; set; }
#nullable restore
#else
        public List<string> Tags { get; set; }
#endif
        /// <summary>The win_probability property</summary>
        public long? WinProbability { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Copper.OpenApiClient.Models.ListOpportunitiesSearch200ResponseItem"/> and sets the default values.
        /// </summary>
        public ListOpportunitiesSearch200ResponseItem()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Copper.OpenApiClient.Models.ListOpportunitiesSearch200ResponseItem"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Copper.OpenApiClient.Models.ListOpportunitiesSearch200ResponseItem CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Copper.OpenApiClient.Models.ListOpportunitiesSearch200ResponseItem();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "assignee_id", n => { AssigneeId = n.GetLongValue(); } },
                { "close_date", n => { CloseDate = n.GetStringValue(); } },
                { "company_id", n => { CompanyId = n.GetLongValue(); } },
                { "company_name", n => { CompanyName = n.GetStringValue(); } },
                { "custom_fields", n => { CustomFields = n.GetCollectionOfObjectValues<global::Soenneker.Copper.OpenApiClient.Models.ListOpportunitiesSearch200ResponseItemCustomFieldsItem>(global::Soenneker.Copper.OpenApiClient.Models.ListOpportunitiesSearch200ResponseItemCustomFieldsItem.CreateFromDiscriminatorValue)?.AsList(); } },
                { "customer_source_id", n => { CustomerSourceId = n.GetLongValue(); } },
                { "date_created", n => { DateCreated = n.GetLongValue(); } },
                { "date_last_contacted", n => { DateLastContacted = n.GetLongValue(); } },
                { "date_lead_created", n => { DateLeadCreated = n.GetLongValue(); } },
                { "date_modified", n => { DateModified = n.GetLongValue(); } },
                { "date_stage_changed", n => { DateStageChanged = n.GetLongValue(); } },
                { "details", n => { Details = n.GetStringValue(); } },
                { "id", n => { Id = n.GetLongValue(); } },
                { "interaction_count", n => { InteractionCount = n.GetLongValue(); } },
                { "leads_converted_from", n => { LeadsConvertedFrom = n.GetCollectionOfObjectValues<global::Soenneker.Copper.OpenApiClient.Models.ListOpportunitiesSearch200ResponseItemLeadsConvertedFromItem>(global::Soenneker.Copper.OpenApiClient.Models.ListOpportunitiesSearch200ResponseItemLeadsConvertedFromItem.CreateFromDiscriminatorValue)?.AsList(); } },
                { "loss_reason_id", n => { LossReasonId = n.GetObjectValue<UntypedNode>(UntypedNode.CreateFromDiscriminatorValue); } },
                { "monetary_unit", n => { MonetaryUnit = n.GetStringValue(); } },
                { "monetary_value", n => { MonetaryValue = n.GetLongValue(); } },
                { "name", n => { Name = n.GetStringValue(); } },
                { "pipeline_id", n => { PipelineId = n.GetLongValue(); } },
                { "pipeline_stage_id", n => { PipelineStageId = n.GetLongValue(); } },
                { "primary_contact_id", n => { PrimaryContactId = n.GetLongValue(); } },
                { "priority", n => { Priority = n.GetStringValue(); } },
                { "status", n => { Status = n.GetStringValue(); } },
                { "tags", n => { Tags = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "win_probability", n => { WinProbability = n.GetLongValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteLongValue("assignee_id", AssigneeId);
            writer.WriteStringValue("close_date", CloseDate);
            writer.WriteLongValue("company_id", CompanyId);
            writer.WriteStringValue("company_name", CompanyName);
            writer.WriteLongValue("customer_source_id", CustomerSourceId);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Copper.OpenApiClient.Models.ListOpportunitiesSearch200ResponseItemCustomFieldsItem>("custom_fields", CustomFields);
            writer.WriteLongValue("date_created", DateCreated);
            writer.WriteLongValue("date_last_contacted", DateLastContacted);
            writer.WriteLongValue("date_lead_created", DateLeadCreated);
            writer.WriteLongValue("date_modified", DateModified);
            writer.WriteLongValue("date_stage_changed", DateStageChanged);
            writer.WriteStringValue("details", Details);
            writer.WriteLongValue("id", Id);
            writer.WriteLongValue("interaction_count", InteractionCount);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Copper.OpenApiClient.Models.ListOpportunitiesSearch200ResponseItemLeadsConvertedFromItem>("leads_converted_from", LeadsConvertedFrom);
            writer.WriteObjectValue<UntypedNode>("loss_reason_id", LossReasonId);
            writer.WriteStringValue("monetary_unit", MonetaryUnit);
            writer.WriteLongValue("monetary_value", MonetaryValue);
            writer.WriteStringValue("name", Name);
            writer.WriteLongValue("pipeline_id", PipelineId);
            writer.WriteLongValue("pipeline_stage_id", PipelineStageId);
            writer.WriteLongValue("primary_contact_id", PrimaryContactId);
            writer.WriteStringValue("priority", Priority);
            writer.WriteStringValue("status", Status);
            writer.WriteCollectionOfPrimitiveValues<string>("tags", Tags);
            writer.WriteLongValue("win_probability", WinProbability);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
