// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Copper.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class ListProjectsSearch200ResponseItem : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The address property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Copper.OpenApiClient.Models.ListProjectsSearch200ResponseItemAddress? Address { get; set; }
#nullable restore
#else
        public global::Soenneker.Copper.OpenApiClient.Models.ListProjectsSearch200ResponseItemAddress Address { get; set; }
#endif
        /// <summary>The assignee_id property</summary>
        public long? AssigneeId { get; set; }
        /// <summary>The contact_type_id property</summary>
        public long? ContactTypeId { get; set; }
        /// <summary>The custom_fields property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Copper.OpenApiClient.Models.ListProjectsSearch200ResponseItemCustomFieldsItem>? CustomFields { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Copper.OpenApiClient.Models.ListProjectsSearch200ResponseItemCustomFieldsItem> CustomFields { get; set; }
#endif
        /// <summary>The date_created property</summary>
        public long? DateCreated { get; set; }
        /// <summary>The date_modified property</summary>
        public long? DateModified { get; set; }
        /// <summary>The details property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Details { get; set; }
#nullable restore
#else
        public string Details { get; set; }
#endif
        /// <summary>The email_domain property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? EmailDomain { get; set; }
#nullable restore
#else
        public string EmailDomain { get; set; }
#endif
        /// <summary>The id property</summary>
        public long? Id { get; set; }
        /// <summary>The interaction_count property</summary>
        public long? InteractionCount { get; set; }
        /// <summary>The name property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Name { get; set; }
#nullable restore
#else
        public string Name { get; set; }
#endif
        /// <summary>The phone_numbers property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Copper.OpenApiClient.Models.ListProjectsSearch200ResponseItemPhoneNumbersItem>? PhoneNumbers { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Copper.OpenApiClient.Models.ListProjectsSearch200ResponseItemPhoneNumbersItem> PhoneNumbers { get; set; }
#endif
        /// <summary>The related_resource property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Copper.OpenApiClient.Models.ListProjectsSearch200ResponseItemRelatedResource? RelatedResource { get; set; }
#nullable restore
#else
        public global::Soenneker.Copper.OpenApiClient.Models.ListProjectsSearch200ResponseItemRelatedResource RelatedResource { get; set; }
#endif
        /// <summary>The socials property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Copper.OpenApiClient.Models.ListProjectsSearch200ResponseItemSocialsItem>? Socials { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Copper.OpenApiClient.Models.ListProjectsSearch200ResponseItemSocialsItem> Socials { get; set; }
#endif
        /// <summary>The status property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Status { get; set; }
#nullable restore
#else
        public string Status { get; set; }
#endif
        /// <summary>The tags property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? Tags { get; set; }
#nullable restore
#else
        public List<string> Tags { get; set; }
#endif
        /// <summary>The websites property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Copper.OpenApiClient.Models.ListProjectsSearch200ResponseItemWebsitesItem>? Websites { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Copper.OpenApiClient.Models.ListProjectsSearch200ResponseItemWebsitesItem> Websites { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Copper.OpenApiClient.Models.ListProjectsSearch200ResponseItem"/> and sets the default values.
        /// </summary>
        public ListProjectsSearch200ResponseItem()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Copper.OpenApiClient.Models.ListProjectsSearch200ResponseItem"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Copper.OpenApiClient.Models.ListProjectsSearch200ResponseItem CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Copper.OpenApiClient.Models.ListProjectsSearch200ResponseItem();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "address", n => { Address = n.GetObjectValue<global::Soenneker.Copper.OpenApiClient.Models.ListProjectsSearch200ResponseItemAddress>(global::Soenneker.Copper.OpenApiClient.Models.ListProjectsSearch200ResponseItemAddress.CreateFromDiscriminatorValue); } },
                { "assignee_id", n => { AssigneeId = n.GetLongValue(); } },
                { "contact_type_id", n => { ContactTypeId = n.GetLongValue(); } },
                { "custom_fields", n => { CustomFields = n.GetCollectionOfObjectValues<global::Soenneker.Copper.OpenApiClient.Models.ListProjectsSearch200ResponseItemCustomFieldsItem>(global::Soenneker.Copper.OpenApiClient.Models.ListProjectsSearch200ResponseItemCustomFieldsItem.CreateFromDiscriminatorValue)?.AsList(); } },
                { "date_created", n => { DateCreated = n.GetLongValue(); } },
                { "date_modified", n => { DateModified = n.GetLongValue(); } },
                { "details", n => { Details = n.GetStringValue(); } },
                { "email_domain", n => { EmailDomain = n.GetStringValue(); } },
                { "id", n => { Id = n.GetLongValue(); } },
                { "interaction_count", n => { InteractionCount = n.GetLongValue(); } },
                { "name", n => { Name = n.GetStringValue(); } },
                { "phone_numbers", n => { PhoneNumbers = n.GetCollectionOfObjectValues<global::Soenneker.Copper.OpenApiClient.Models.ListProjectsSearch200ResponseItemPhoneNumbersItem>(global::Soenneker.Copper.OpenApiClient.Models.ListProjectsSearch200ResponseItemPhoneNumbersItem.CreateFromDiscriminatorValue)?.AsList(); } },
                { "related_resource", n => { RelatedResource = n.GetObjectValue<global::Soenneker.Copper.OpenApiClient.Models.ListProjectsSearch200ResponseItemRelatedResource>(global::Soenneker.Copper.OpenApiClient.Models.ListProjectsSearch200ResponseItemRelatedResource.CreateFromDiscriminatorValue); } },
                { "socials", n => { Socials = n.GetCollectionOfObjectValues<global::Soenneker.Copper.OpenApiClient.Models.ListProjectsSearch200ResponseItemSocialsItem>(global::Soenneker.Copper.OpenApiClient.Models.ListProjectsSearch200ResponseItemSocialsItem.CreateFromDiscriminatorValue)?.AsList(); } },
                { "status", n => { Status = n.GetStringValue(); } },
                { "tags", n => { Tags = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "websites", n => { Websites = n.GetCollectionOfObjectValues<global::Soenneker.Copper.OpenApiClient.Models.ListProjectsSearch200ResponseItemWebsitesItem>(global::Soenneker.Copper.OpenApiClient.Models.ListProjectsSearch200ResponseItemWebsitesItem.CreateFromDiscriminatorValue)?.AsList(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::Soenneker.Copper.OpenApiClient.Models.ListProjectsSearch200ResponseItemAddress>("address", Address);
            writer.WriteLongValue("assignee_id", AssigneeId);
            writer.WriteLongValue("contact_type_id", ContactTypeId);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Copper.OpenApiClient.Models.ListProjectsSearch200ResponseItemCustomFieldsItem>("custom_fields", CustomFields);
            writer.WriteLongValue("date_created", DateCreated);
            writer.WriteLongValue("date_modified", DateModified);
            writer.WriteStringValue("details", Details);
            writer.WriteStringValue("email_domain", EmailDomain);
            writer.WriteLongValue("id", Id);
            writer.WriteLongValue("interaction_count", InteractionCount);
            writer.WriteStringValue("name", Name);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Copper.OpenApiClient.Models.ListProjectsSearch200ResponseItemPhoneNumbersItem>("phone_numbers", PhoneNumbers);
            writer.WriteObjectValue<global::Soenneker.Copper.OpenApiClient.Models.ListProjectsSearch200ResponseItemRelatedResource>("related_resource", RelatedResource);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Copper.OpenApiClient.Models.ListProjectsSearch200ResponseItemSocialsItem>("socials", Socials);
            writer.WriteStringValue("status", Status);
            writer.WriteCollectionOfPrimitiveValues<string>("tags", Tags);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Copper.OpenApiClient.Models.ListProjectsSearch200ResponseItemWebsitesItem>("websites", Websites);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
