// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Copper.OpenApiClient.Models
{
    /// <summary>
    /// Composed type wrapper for classes <see cref="bool"/>, <see cref="long"/>, List&lt;long&gt;
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class ListTasksSearch200ResponseItemCustomFieldsItemValue : IComposedTypeWrapper, IParsable
    {
        /// <summary>Composed type representation for type <see cref="bool"/></summary>
        public bool? Boolean { get; set; }
        /// <summary>Composed type representation for type List&lt;long&gt;</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<long?>? Int64 { get; set; }
#nullable restore
#else
        public List<long?> Int64 { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="long"/></summary>
        public long? ListTasksSearch200ResponseItemCustomFieldsItemValueInt64 { get; set; }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Copper.OpenApiClient.Models.ListTasksSearch200ResponseItemCustomFieldsItemValue"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Copper.OpenApiClient.Models.ListTasksSearch200ResponseItemCustomFieldsItemValue CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            var result = new global::Soenneker.Copper.OpenApiClient.Models.ListTasksSearch200ResponseItemCustomFieldsItemValue();
            if(parseNode.GetBoolValue() is bool booleanValue)
            {
                result.Boolean = booleanValue;
            }
            else if(parseNode.GetLongValue() is long listTasksSearch200ResponseItemCustomFieldsItemValueInt64Value)
            {
                result.ListTasksSearch200ResponseItemCustomFieldsItemValueInt64 = listTasksSearch200ResponseItemCustomFieldsItemValueInt64Value;
            }
            else if(parseNode.GetCollectionOfPrimitiveValues<long?>()?.AsList() is List<long?> int64Value)
            {
                result.Int64 = int64Value;
            }
            return result;
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>();
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            if(Boolean != null)
            {
                writer.WriteBoolValue(null, Boolean);
            }
            else if(ListTasksSearch200ResponseItemCustomFieldsItemValueInt64 != null)
            {
                writer.WriteLongValue(null, ListTasksSearch200ResponseItemCustomFieldsItemValueInt64);
            }
            else if(Int64 != null)
            {
                writer.WriteCollectionOfPrimitiveValues<long?>(null, Int64);
            }
        }
    }
}
#pragma warning restore CS0618
