// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Copper.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class SeeACompanySActivities200ResponseItem : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>The activity_date property</summary>
        public int? ActivityDate { get; set; }
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The date_created property</summary>
        public int? DateCreated { get; set; }
        /// <summary>The date_modified property</summary>
        public int? DateModified { get; set; }
        /// <summary>The details property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Details { get; set; }
#nullable restore
#else
        public string Details { get; set; }
#endif
        /// <summary>The id property</summary>
        public int? Id { get; set; }
        /// <summary>The new_value property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? NewValue { get; set; }
#nullable restore
#else
        public string NewValue { get; set; }
#endif
        /// <summary>The old_value property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? OldValue { get; set; }
#nullable restore
#else
        public string OldValue { get; set; }
#endif
        /// <summary>The parent property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Copper.OpenApiClient.Models.SeeACompanySActivities200ResponseItemParent? Parent { get; set; }
#nullable restore
#else
        public global::Soenneker.Copper.OpenApiClient.Models.SeeACompanySActivities200ResponseItemParent Parent { get; set; }
#endif
        /// <summary>The type property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Copper.OpenApiClient.Models.SeeACompanySActivities200ResponseItemType? Type { get; set; }
#nullable restore
#else
        public global::Soenneker.Copper.OpenApiClient.Models.SeeACompanySActivities200ResponseItemType Type { get; set; }
#endif
        /// <summary>The user_id property</summary>
        public int? UserId { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Copper.OpenApiClient.Models.SeeACompanySActivities200ResponseItem"/> and sets the default values.
        /// </summary>
        public SeeACompanySActivities200ResponseItem()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Copper.OpenApiClient.Models.SeeACompanySActivities200ResponseItem"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Copper.OpenApiClient.Models.SeeACompanySActivities200ResponseItem CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Copper.OpenApiClient.Models.SeeACompanySActivities200ResponseItem();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "activity_date", n => { ActivityDate = n.GetIntValue(); } },
                { "date_created", n => { DateCreated = n.GetIntValue(); } },
                { "date_modified", n => { DateModified = n.GetIntValue(); } },
                { "details", n => { Details = n.GetStringValue(); } },
                { "id", n => { Id = n.GetIntValue(); } },
                { "new_value", n => { NewValue = n.GetStringValue(); } },
                { "old_value", n => { OldValue = n.GetStringValue(); } },
                { "parent", n => { Parent = n.GetObjectValue<global::Soenneker.Copper.OpenApiClient.Models.SeeACompanySActivities200ResponseItemParent>(global::Soenneker.Copper.OpenApiClient.Models.SeeACompanySActivities200ResponseItemParent.CreateFromDiscriminatorValue); } },
                { "type", n => { Type = n.GetObjectValue<global::Soenneker.Copper.OpenApiClient.Models.SeeACompanySActivities200ResponseItemType>(global::Soenneker.Copper.OpenApiClient.Models.SeeACompanySActivities200ResponseItemType.CreateFromDiscriminatorValue); } },
                { "user_id", n => { UserId = n.GetIntValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteIntValue("activity_date", ActivityDate);
            writer.WriteIntValue("date_created", DateCreated);
            writer.WriteIntValue("date_modified", DateModified);
            writer.WriteStringValue("details", Details);
            writer.WriteIntValue("id", Id);
            writer.WriteStringValue("new_value", NewValue);
            writer.WriteStringValue("old_value", OldValue);
            writer.WriteObjectValue<global::Soenneker.Copper.OpenApiClient.Models.SeeACompanySActivities200ResponseItemParent>("parent", Parent);
            writer.WriteObjectValue<global::Soenneker.Copper.OpenApiClient.Models.SeeACompanySActivities200ResponseItemType>("type", Type);
            writer.WriteIntValue("user_id", UserId);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
