// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Copper.OpenApiClient.Models
{
    /// <summary>
    /// Composed type wrapper for classes <see cref="long"/>, <see cref="string"/>, List&lt;long&gt;
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class UpdateALead200ResponseCustomFieldsItemValue : IComposedTypeWrapper, IParsable
    {
        /// <summary>Composed type representation for type List&lt;long&gt;</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<long?>? Int64 { get; set; }
#nullable restore
#else
        public List<long?> Int64 { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="string"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? String { get; set; }
#nullable restore
#else
        public string String { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="long"/></summary>
        public long? UpdateALead200ResponseCustomFieldsItemValueInt64 { get; set; }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Copper.OpenApiClient.Models.UpdateALead200ResponseCustomFieldsItemValue"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Copper.OpenApiClient.Models.UpdateALead200ResponseCustomFieldsItemValue CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            var result = new global::Soenneker.Copper.OpenApiClient.Models.UpdateALead200ResponseCustomFieldsItemValue();
            if(parseNode.GetStringValue() is string stringValue)
            {
                result.String = stringValue;
            }
            else if(parseNode.GetLongValue() is long updateALead200ResponseCustomFieldsItemValueInt64Value)
            {
                result.UpdateALead200ResponseCustomFieldsItemValueInt64 = updateALead200ResponseCustomFieldsItemValueInt64Value;
            }
            else if(parseNode.GetCollectionOfPrimitiveValues<long?>()?.AsList() is List<long?> int64Value)
            {
                result.Int64 = int64Value;
            }
            return result;
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>();
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            if(String != null)
            {
                writer.WriteStringValue(null, String);
            }
            else if(UpdateALead200ResponseCustomFieldsItemValueInt64 != null)
            {
                writer.WriteLongValue(null, UpdateALead200ResponseCustomFieldsItemValueInt64);
            }
            else if(Int64 != null)
            {
                writer.WriteCollectionOfPrimitiveValues<long?>(null, Int64);
            }
        }
    }
}
#pragma warning restore CS0618
