// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Copper.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class Upload1GetSignedS3Url200Response : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The body property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Copper.OpenApiClient.Models.Upload1GetSignedS3Url200ResponseBody? Body { get; set; }
#nullable restore
#else
        public global::Soenneker.Copper.OpenApiClient.Models.Upload1GetSignedS3Url200ResponseBody Body { get; set; }
#endif
        /// <summary>The method property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Method { get; set; }
#nullable restore
#else
        public string Method { get; set; }
#endif
        /// <summary>The removed property</summary>
        public bool? Removed { get; set; }
        /// <summary>The resource property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Copper.OpenApiClient.Models.Upload1GetSignedS3Url200ResponseResource? Resource { get; set; }
#nullable restore
#else
        public global::Soenneker.Copper.OpenApiClient.Models.Upload1GetSignedS3Url200ResponseResource Resource { get; set; }
#endif
        /// <summary>The sample_curl property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? SampleCurl { get; set; }
#nullable restore
#else
        public string SampleCurl { get; set; }
#endif
        /// <summary>The url property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Url { get; set; }
#nullable restore
#else
        public string Url { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Copper.OpenApiClient.Models.Upload1GetSignedS3Url200Response"/> and sets the default values.
        /// </summary>
        public Upload1GetSignedS3Url200Response()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Copper.OpenApiClient.Models.Upload1GetSignedS3Url200Response"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Copper.OpenApiClient.Models.Upload1GetSignedS3Url200Response CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Copper.OpenApiClient.Models.Upload1GetSignedS3Url200Response();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "body", n => { Body = n.GetObjectValue<global::Soenneker.Copper.OpenApiClient.Models.Upload1GetSignedS3Url200ResponseBody>(global::Soenneker.Copper.OpenApiClient.Models.Upload1GetSignedS3Url200ResponseBody.CreateFromDiscriminatorValue); } },
                { "method", n => { Method = n.GetStringValue(); } },
                { "removed", n => { Removed = n.GetBoolValue(); } },
                { "resource", n => { Resource = n.GetObjectValue<global::Soenneker.Copper.OpenApiClient.Models.Upload1GetSignedS3Url200ResponseResource>(global::Soenneker.Copper.OpenApiClient.Models.Upload1GetSignedS3Url200ResponseResource.CreateFromDiscriminatorValue); } },
                { "sample_curl", n => { SampleCurl = n.GetStringValue(); } },
                { "url", n => { Url = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::Soenneker.Copper.OpenApiClient.Models.Upload1GetSignedS3Url200ResponseBody>("body", Body);
            writer.WriteStringValue("method", Method);
            writer.WriteBoolValue("removed", Removed);
            writer.WriteObjectValue<global::Soenneker.Copper.OpenApiClient.Models.Upload1GetSignedS3Url200ResponseResource>("resource", Resource);
            writer.WriteStringValue("sample_curl", SampleCurl);
            writer.WriteStringValue("url", Url);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
