// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Copper.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class Upload3RelateTheUploadedFileToASpecificEntity200Response : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The content_type property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ContentType { get; set; }
#nullable restore
#else
        public string ContentType { get; set; }
#endif
        /// <summary>The creator_id property</summary>
        public int? CreatorId { get; set; }
        /// <summary>The date_created property</summary>
        public int? DateCreated { get; set; }
        /// <summary>The date_modified property</summary>
        public int? DateModified { get; set; }
        /// <summary>The file_name property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? FileName { get; set; }
#nullable restore
#else
        public string FileName { get; set; }
#endif
        /// <summary>The file_size property</summary>
        public int? FileSize { get; set; }
        /// <summary>The id property</summary>
        public int? Id { get; set; }
        /// <summary>The is_deleted property</summary>
        public bool? IsDeleted { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Copper.OpenApiClient.Models.Upload3RelateTheUploadedFileToASpecificEntity200Response"/> and sets the default values.
        /// </summary>
        public Upload3RelateTheUploadedFileToASpecificEntity200Response()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Copper.OpenApiClient.Models.Upload3RelateTheUploadedFileToASpecificEntity200Response"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Copper.OpenApiClient.Models.Upload3RelateTheUploadedFileToASpecificEntity200Response CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Copper.OpenApiClient.Models.Upload3RelateTheUploadedFileToASpecificEntity200Response();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "content_type", n => { ContentType = n.GetStringValue(); } },
                { "creator_id", n => { CreatorId = n.GetIntValue(); } },
                { "date_created", n => { DateCreated = n.GetIntValue(); } },
                { "date_modified", n => { DateModified = n.GetIntValue(); } },
                { "file_name", n => { FileName = n.GetStringValue(); } },
                { "file_size", n => { FileSize = n.GetIntValue(); } },
                { "id", n => { Id = n.GetIntValue(); } },
                { "is_deleted", n => { IsDeleted = n.GetBoolValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("content_type", ContentType);
            writer.WriteIntValue("creator_id", CreatorId);
            writer.WriteIntValue("date_created", DateCreated);
            writer.WriteIntValue("date_modified", DateModified);
            writer.WriteStringValue("file_name", FileName);
            writer.WriteIntValue("file_size", FileSize);
            writer.WriteIntValue("id", Id);
            writer.WriteBoolValue("is_deleted", IsDeleted);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
