// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Copper.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class UpsertaLead200Response : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The address property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public UntypedNode? Address { get; set; }
#nullable restore
#else
        public UntypedNode Address { get; set; }
#endif
        /// <summary>The assignee_id property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public UntypedNode? AssigneeId { get; set; }
#nullable restore
#else
        public UntypedNode AssigneeId { get; set; }
#endif
        /// <summary>The company_name property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public UntypedNode? CompanyName { get; set; }
#nullable restore
#else
        public UntypedNode CompanyName { get; set; }
#endif
        /// <summary>The customer_source_id property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public UntypedNode? CustomerSourceId { get; set; }
#nullable restore
#else
        public UntypedNode CustomerSourceId { get; set; }
#endif
        /// <summary>The custom_fields property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Copper.OpenApiClient.Models.UpsertaLead200ResponseCustomFieldsItem>? CustomFields { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Copper.OpenApiClient.Models.UpsertaLead200ResponseCustomFieldsItem> CustomFields { get; set; }
#endif
        /// <summary>The date_created property</summary>
        public long? DateCreated { get; set; }
        /// <summary>The date_last_contacted property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public UntypedNode? DateLastContacted { get; set; }
#nullable restore
#else
        public UntypedNode DateLastContacted { get; set; }
#endif
        /// <summary>The date_modified property</summary>
        public long? DateModified { get; set; }
        /// <summary>The details property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public UntypedNode? Details { get; set; }
#nullable restore
#else
        public UntypedNode Details { get; set; }
#endif
        /// <summary>The email property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Copper.OpenApiClient.Models.UpsertaLead200ResponseEmail? Email { get; set; }
#nullable restore
#else
        public global::Soenneker.Copper.OpenApiClient.Models.UpsertaLead200ResponseEmail Email { get; set; }
#endif
        /// <summary>The first_name property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? FirstName { get; set; }
#nullable restore
#else
        public string FirstName { get; set; }
#endif
        /// <summary>The id property</summary>
        public long? Id { get; set; }
        /// <summary>The interaction_count property</summary>
        public long? InteractionCount { get; set; }
        /// <summary>The last_name property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? LastName { get; set; }
#nullable restore
#else
        public string LastName { get; set; }
#endif
        /// <summary>The middle_name property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public UntypedNode? MiddleName { get; set; }
#nullable restore
#else
        public UntypedNode MiddleName { get; set; }
#endif
        /// <summary>The monetary_unit property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public UntypedNode? MonetaryUnit { get; set; }
#nullable restore
#else
        public UntypedNode MonetaryUnit { get; set; }
#endif
        /// <summary>The monetary_value property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public UntypedNode? MonetaryValue { get; set; }
#nullable restore
#else
        public UntypedNode MonetaryValue { get; set; }
#endif
        /// <summary>The name property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Name { get; set; }
#nullable restore
#else
        public string Name { get; set; }
#endif
        /// <summary>The phone_numbers property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public UntypedNode? PhoneNumbers { get; set; }
#nullable restore
#else
        public UntypedNode PhoneNumbers { get; set; }
#endif
        /// <summary>The prefix property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public UntypedNode? Prefix { get; set; }
#nullable restore
#else
        public UntypedNode Prefix { get; set; }
#endif
        /// <summary>The socials property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public UntypedNode? Socials { get; set; }
#nullable restore
#else
        public UntypedNode Socials { get; set; }
#endif
        /// <summary>The status property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Status { get; set; }
#nullable restore
#else
        public string Status { get; set; }
#endif
        /// <summary>The status_id property</summary>
        public long? StatusId { get; set; }
        /// <summary>The suffix property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public UntypedNode? Suffix { get; set; }
#nullable restore
#else
        public UntypedNode Suffix { get; set; }
#endif
        /// <summary>The tags property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public UntypedNode? Tags { get; set; }
#nullable restore
#else
        public UntypedNode Tags { get; set; }
#endif
        /// <summary>The title property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public UntypedNode? Title { get; set; }
#nullable restore
#else
        public UntypedNode Title { get; set; }
#endif
        /// <summary>The websites property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public UntypedNode? Websites { get; set; }
#nullable restore
#else
        public UntypedNode Websites { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Copper.OpenApiClient.Models.UpsertaLead200Response"/> and sets the default values.
        /// </summary>
        public UpsertaLead200Response()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Copper.OpenApiClient.Models.UpsertaLead200Response"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Copper.OpenApiClient.Models.UpsertaLead200Response CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Copper.OpenApiClient.Models.UpsertaLead200Response();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "address", n => { Address = n.GetObjectValue<UntypedNode>(UntypedNode.CreateFromDiscriminatorValue); } },
                { "assignee_id", n => { AssigneeId = n.GetObjectValue<UntypedNode>(UntypedNode.CreateFromDiscriminatorValue); } },
                { "company_name", n => { CompanyName = n.GetObjectValue<UntypedNode>(UntypedNode.CreateFromDiscriminatorValue); } },
                { "custom_fields", n => { CustomFields = n.GetCollectionOfObjectValues<global::Soenneker.Copper.OpenApiClient.Models.UpsertaLead200ResponseCustomFieldsItem>(global::Soenneker.Copper.OpenApiClient.Models.UpsertaLead200ResponseCustomFieldsItem.CreateFromDiscriminatorValue)?.AsList(); } },
                { "customer_source_id", n => { CustomerSourceId = n.GetObjectValue<UntypedNode>(UntypedNode.CreateFromDiscriminatorValue); } },
                { "date_created", n => { DateCreated = n.GetLongValue(); } },
                { "date_last_contacted", n => { DateLastContacted = n.GetObjectValue<UntypedNode>(UntypedNode.CreateFromDiscriminatorValue); } },
                { "date_modified", n => { DateModified = n.GetLongValue(); } },
                { "details", n => { Details = n.GetObjectValue<UntypedNode>(UntypedNode.CreateFromDiscriminatorValue); } },
                { "email", n => { Email = n.GetObjectValue<global::Soenneker.Copper.OpenApiClient.Models.UpsertaLead200ResponseEmail>(global::Soenneker.Copper.OpenApiClient.Models.UpsertaLead200ResponseEmail.CreateFromDiscriminatorValue); } },
                { "first_name", n => { FirstName = n.GetStringValue(); } },
                { "id", n => { Id = n.GetLongValue(); } },
                { "interaction_count", n => { InteractionCount = n.GetLongValue(); } },
                { "last_name", n => { LastName = n.GetStringValue(); } },
                { "middle_name", n => { MiddleName = n.GetObjectValue<UntypedNode>(UntypedNode.CreateFromDiscriminatorValue); } },
                { "monetary_unit", n => { MonetaryUnit = n.GetObjectValue<UntypedNode>(UntypedNode.CreateFromDiscriminatorValue); } },
                { "monetary_value", n => { MonetaryValue = n.GetObjectValue<UntypedNode>(UntypedNode.CreateFromDiscriminatorValue); } },
                { "name", n => { Name = n.GetStringValue(); } },
                { "phone_numbers", n => { PhoneNumbers = n.GetObjectValue<UntypedNode>(UntypedNode.CreateFromDiscriminatorValue); } },
                { "prefix", n => { Prefix = n.GetObjectValue<UntypedNode>(UntypedNode.CreateFromDiscriminatorValue); } },
                { "socials", n => { Socials = n.GetObjectValue<UntypedNode>(UntypedNode.CreateFromDiscriminatorValue); } },
                { "status", n => { Status = n.GetStringValue(); } },
                { "status_id", n => { StatusId = n.GetLongValue(); } },
                { "suffix", n => { Suffix = n.GetObjectValue<UntypedNode>(UntypedNode.CreateFromDiscriminatorValue); } },
                { "tags", n => { Tags = n.GetObjectValue<UntypedNode>(UntypedNode.CreateFromDiscriminatorValue); } },
                { "title", n => { Title = n.GetObjectValue<UntypedNode>(UntypedNode.CreateFromDiscriminatorValue); } },
                { "websites", n => { Websites = n.GetObjectValue<UntypedNode>(UntypedNode.CreateFromDiscriminatorValue); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<UntypedNode>("address", Address);
            writer.WriteObjectValue<UntypedNode>("assignee_id", AssigneeId);
            writer.WriteObjectValue<UntypedNode>("company_name", CompanyName);
            writer.WriteObjectValue<UntypedNode>("customer_source_id", CustomerSourceId);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Copper.OpenApiClient.Models.UpsertaLead200ResponseCustomFieldsItem>("custom_fields", CustomFields);
            writer.WriteLongValue("date_created", DateCreated);
            writer.WriteObjectValue<UntypedNode>("date_last_contacted", DateLastContacted);
            writer.WriteLongValue("date_modified", DateModified);
            writer.WriteObjectValue<UntypedNode>("details", Details);
            writer.WriteObjectValue<global::Soenneker.Copper.OpenApiClient.Models.UpsertaLead200ResponseEmail>("email", Email);
            writer.WriteStringValue("first_name", FirstName);
            writer.WriteLongValue("id", Id);
            writer.WriteLongValue("interaction_count", InteractionCount);
            writer.WriteStringValue("last_name", LastName);
            writer.WriteObjectValue<UntypedNode>("middle_name", MiddleName);
            writer.WriteObjectValue<UntypedNode>("monetary_unit", MonetaryUnit);
            writer.WriteObjectValue<UntypedNode>("monetary_value", MonetaryValue);
            writer.WriteStringValue("name", Name);
            writer.WriteObjectValue<UntypedNode>("phone_numbers", PhoneNumbers);
            writer.WriteObjectValue<UntypedNode>("prefix", Prefix);
            writer.WriteObjectValue<UntypedNode>("socials", Socials);
            writer.WriteStringValue("status", Status);
            writer.WriteLongValue("status_id", StatusId);
            writer.WriteObjectValue<UntypedNode>("suffix", Suffix);
            writer.WriteObjectValue<UntypedNode>("tags", Tags);
            writer.WriteObjectValue<UntypedNode>("title", Title);
            writer.WriteObjectValue<UntypedNode>("websites", Websites);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
